server:
  servlet:
    context-path: /aa/api
    session:
      timeout: 28800
  server-header:


attribute_authorities_config_path: classpath:/attributeAuthorities.yml
authorization_access_token_url: https://authz.test2.surfconext.nl/oauth/token
aggregate_cache_duration_milliseconds: -1

orcid:
  authorization_uri: https://sandbox.orcid.org/oauth/authorize
  access_token_uri: https://sandbox.orcid.org/oauth/token
  client_id:
  client_secret:
  redirect_uri: http://localhost:8080/aa/api/redirect


security:
  internal_user_name: eb
  internal_password: secret

api:
  lifecycle:
    username: life
    password: secret

pseudo:
  mail_postfix: surfconext.nl

spring:
  jpa:
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.MariaDB53Dialect
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost/aaserver?autoReconnect=true&useSSL=false
    username: root
    password:
  main:
    banner-mode: "off"
  flyway:
    validate-on-migrate: false
    table: schema_version

# In a multi master database setup toggle which machine is reponsible for cron jobs
cron_job_responsible: true
pseudo_emails_retention_days_period: 90


# We disable all endpoints except health for the load-balancer and info for git information.
management:
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: "/internal"
  endpoint:
    info:
      enabled: true
  info:
    git:
      mode: full

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
